kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi