apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: front
  labels:
    app: front-service
spec:
  type: LoadBalancer  
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: front
  labels:
    app: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        imagePullPolicy: Always
        image: mbiostudyregistry.azurecr.io/make-blog-front:1.1-SNAPSHOT
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "96Mi"
            cpu: "0.2"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3