apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mysql-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # nodeSelector:
      #   "beta.kubernetes.io/os": linux
      containers:
      - image: mysql:5.6
        imagePullPolicy: "IfNotPresent"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql/
        - name: config-volume
          mountPath: /etc/mysql/mysql.conf.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: config-volume
        configMap:
          name: mysql-config
          optional: true