apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
          fsGroup: 2000
      containers:
      - image: sonatype/nexus3:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4Gi"
            cpu: "4000m"
          requests:
            memory: "2Gi"
            cpu: "500m"
        name: nexus
        ports:
        - containerPort: 8081
        - containerPort: 5000
        volumeMounts:
          - name: nexus-data-volume
            mountPath: /nexus-data  
      volumes:
        - name: nexus-data-volume
          persistentVolumeClaim:
            claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: default
spec:
  selector:
    app: nexus
  type: LoadBalancer  
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: docker 